import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ThemeProvider from "@/components/ThemeProvider";

const outfit = Outfit({
  variable: "--font-Outfit",
  subsets: ["latin"],
});



export const metadata = {
  title: "Ahmed Abdelelah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfit.className}  antialiased`}
      >
        <ThemeProvider attribute='class' defaultTheme='light'>
        <Header/>
        {children}
        <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}


// 1. Added ===================================================>suppressHydrationWarning =====================================on <html>

// This is required by next-themes to avoid hydration mismatches.
// The <ThemeProvider> must wrap the entire application inside the <body>, but also must not wrap Header and Footer if they use server components — unless your ThemeProvider is a client component (which it is, thanks to "use client").

// 2. ThemeProvider props

// You're passing the correct props:

// attribute="class"
// defaultTheme="light"
// enableSystem